version: "3"

services:
  #PHP Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html/
    volumes:
      - ./backend:/var/www/html/
    networks:
      - app-network

  frontend:
    stdin_open: true
    container_name: frontend
    build:
      context: ./bentador
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./bentador:/var/www/html/
    networks:
      - app-network

  #Nginx Service
  webserver:
    depends_on:
      - backend
      - frontend
    build:
      context: ./backend/nginx
      dockerfile: Dockerfile
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8000:8000"
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge